### ISSUE TITLE
building wheels is failing

### ISSUE THREAD

**Issue by mattip** [Quansight/pnumpy#136]
The build-and-upload github action is failing with something about the wheel already existing. @daletovar could you take a look? [here](https://github.com/Quansight/numpy-threading-extensions/actions/runs/499129715) is one of many failed runs.

**Comment by mattip** [comment]
A version is now available at https://test.pypi.org/project/pnumpy/, but it is has a `post0` suffix. Is that on purpose?

**Comment by tdimitri** [comment]
On pypi normal now.
